# Generated by Django 3.1 on 2020-08-25 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('ship_address', models.CharField(default='address', max_length=100, verbose_name='Delivered to')),
                ('payment_type', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayMaya', 'PayMaya'), ('Gcash', 'Gcash'), ('Bank', 'Bank')], default='Cash on Delivery', max_length=20, verbose_name='Payment Method')),
                ('name', models.CharField(default='Name', max_length=40, verbose_name='Name')),
                ('mobile', models.CharField(default='09', max_length=11, verbose_name='Mobile No.')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Canned Goods', 'Canned Goods'), ('Noodles', 'Noodles'), ('Vegetables', 'Vegetables'), ('Rice', 'Rice')], default='Canned Goods', max_length=20)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_store.order')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='e_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='e_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_address', models.CharField(default='address', max_length=20, verbose_name='Detailed Address: House#/Buildingname/Street')),
                ('brgy_dist_name', models.CharField(max_length=20, verbose_name='Barangay')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('region', models.CharField(default='address', max_length=20, verbose_name='Region')),
                ('province', models.CharField(max_length=20, verbose_name='Province')),
                ('postal_code', models.CharField(default='postal_code here', max_length=20, verbose_name='Postal Code')),
                ('name', models.CharField(default='Please put your name', max_length=20, verbose_name='Name')),
                ('mobile', models.CharField(default='Please update your number', max_length=20, verbose_name='Mobile #')),
                ('distance_to_store', models.IntegerField(default=0, verbose_name='Shipping Distance(km)')),
                ('current', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
