# Generated by Django 3.1 on 2020-08-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='h_b_st_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='st_name',
        ),
        migrations.AddField(
            model_name='address',
            name='detailed_address',
            field=models.CharField(default='address', max_length=20, verbose_name='Detailed Address: House#/Buildingname/Street'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(default='address', max_length=20, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='address',
            name='brgy_dist_name',
            field=models.CharField(max_length=20, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, verbose_name='City'),
        ),
    ]
