# Generated by Django 3.1 on 2020-08-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0002_auto_20200819_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='distance_to_store',
            field=models.IntegerField(default=0, verbose_name='Shipping Distance(km)'),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='Please update your number', max_length=20, verbose_name='Mobile #'),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Please put your name', max_length=20, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='postal_code here', max_length=20, verbose_name='Postal Code'),
        ),
    ]
