# Generated by Django 3.1 on 2020-08-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0003_auto_20200819_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
