# Generated by Django 3.1 on 2020-08-21 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0005_auto_20200820_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_store.product')),
            ],
        ),
    ]
