# Generated by Django 3.1 on 2020-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0005_auto_20200811_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Canned Goods', 'Canned Goods'), ('Noodles', 'Noodles'), ('Vegetables', 'Vegetables'), ('Rice', 'Rice')], default='Canned Goods', max_length=20),
        ),
    ]
