# Generated by Django 3.1 on 2020-08-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0006_auto_20200821_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='09', max_length=11, verbose_name='Mobile No.'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Name', max_length=40, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayMaya', 'PayMaya'), ('Gcash', 'Gcash'), ('Bank', 'Bank')], default='Cash on Delivery', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_address',
            field=models.CharField(default='address', max_length=100, verbose_name='Delivered to'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_store.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='e_store.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
